### ISSUE TITLE
WMLJobImpl.updateStatus() has input file data in the response

### ISSUE THREAD

**Issue by jrobichaud** [IBMDecisionOptimization/DOforWMLwithJava#1]
Original issue:
https://github.com/achabrier/assets/issues/2

WMLJobImpl.updateStatus() calls 

`String res = doGet(url + "/v4/jobs/" + job_id, headers);` to update its status.

Which contains ultimately the input data in the response:

![image](https://user-images.githubusercontent.com/12142702/83139281-1c74cf80-a0ba-11ea-8995-a0dfe9989436.png)

In the case of inline jobs it represents a lot of data in each response and this data is not useful in most cases. It could be a reference url to this data or something.

**Comment by jrobichaud** [comment]
@achabrier could you share the parameter to remove the input of the response you were referring to in the other issue. Thanks.

**Comment by achabrier** [comment]
One question: is this using LP/MPS file inline in payload? If these are huge, I suggest they are passed by reference using Object Storage.

**Comment by achabrier** [comment]
Hi, the parameter is oaas.includeInputData
You couyld add
solve_parameters.put("oaas.includeInputData", "false");
which will remove all the input from the GET jobs as soon as the job is starting.

**Comment by achabrier** [comment]
added in sample code.
